
language: node_js

node_js:
  - "8.4.0"

install:
  - npm install
  - npm install -g firebase-tools

script:
  - npm run build
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/run_on_pull_requests.sh; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis/run_on_master.sh; fi'

branches:
  only:
  - master

cache:
  directories:
- $HOME/.npm